version: "3.9"

services:
  matcher-postgres:
    container_name: postgres
    image: bitnami/postgresql:16.4.0-debian-12-r9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=random_walk_postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
