spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8081}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
  application:
    name: matcher-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "matcher-service"
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
      auto-startup: false

matcher:
  min-walk-time-in-seconds: 3600
  offset-between-walks-in-seconds: 900
  appointment-manager-delay-seconds: 60