spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8081}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
  application:
    name: matcher-service

matcher:
  min-walk-time-in-seconds: 3600
  offset-between-walks-in-seconds: 900