name: ci/cd

on:
  push:

env:
  APP_NAME: matcher-service
  IMAGE_NAME: random-walk-matcher-service
  DOCKER_REPO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-project-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          cache: gradle
          distribution: corretto

      - name: Build Project
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-project-and-push-image
    environment:
      name: approvers

    env:
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Get image tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      # Install helm and gcloud component
      - name: Install components
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash 
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone $GKE_ZONE \
            --project $GKE_PROJECT
          helm upgrade $APP_NAME ./deploy/$APP_NAME/ \
            --set image.tag=$DOCKER_METADATA_OUTPUT_TAGS \
            --set image.repository=$DOCKER_REPO_USERNAME/$IMAGE_NAME \
            --namespace $APP_NAME \
            --install \
            --wait
